
instance_create_layer(x, y, "armas", obj_particula1)
instance_create_layer(x, y, "armas", obj_particula1)
instance_create_layer(x, y, "armas", obj_particula1)
instance_create_layer(x, y, "armas", obj_particula1)
instance_create_layer(x, y, "armas", obj_particula1)
instance_create_layer(x, y, "armas", obj_particula1)
instance_create_layer(x, y, "armas", obj_particula1)
instance_create_layer(x, y, "armas", obj_particula1)
instance_create_layer(x, y, "armas", obj_particula1)
instance_create_layer(x, y, "armas", obj_particula1)
